//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inmobiliaria.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroIngresos
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Tipo { get; set; }
        public decimal Valor { get; set; }
        public decimal Mora { get; set; }
        public decimal Descuento { get; set; }
        public decimal Iva { get; set; }
        public decimal Total { get; set; }
        public int IdCajaBanco { get; set; }
        public Nullable<int> IdCuentasxPagarContratos { get; set; }
        public Nullable<int> IdCuentasxCobrarContratos { get; set; }
        public string Nombre { get; set; }
        public int IdInmobiliaria { get; set; }
    
        public virtual CajaBanco CajaBanco { get; set; }
        public virtual CuentasxCobrarContratos CuentasxCobrarContratos { get; set; }
        public virtual CuentasxPagarContratos CuentasxPagarContratos { get; set; }
        public virtual Inmobiliaria Inmobiliaria { get; set; }
        public virtual TipoPago TipoPago { get; set; }
    }
}
