//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inmobiliaria.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Email { get; set; }
        public string Pass { get; set; }
        public string Estado { get; set; }
        public int Rol { get; set; }
        public Nullable<System.DateTime> FechaAdd { get; set; }
        public int IdInmobiliaria { get; set; }
    
        public virtual Inmobiliaria Inmobiliaria { get; set; }
        public virtual RolesUsuarios RolesUsuarios { get; set; }
    }
}
